import type { NextPage } from 'next'
import Head from 'next/head'

import styles from '../styles/Home.module.css'

import { Canvas } from '@react-three/fiber'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>NP4</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Canvas dpr={window.devicePixelRatio} shadows >
      <ambientLight intensity={0.1} color={0xffffff} />

    </Canvas>
    </div>
  )
}

export default Home
